services:
  - type: web
    name: heildepot-server
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://lichtungooo.github.io/heildepot-prototyp
